var services = [
	{
		title: 'National Enquirer',
		image: 'assets/images/national_enquirer.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'National Examiner',
		image: 'assets/images/national_examiner.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'Globe',
		image: 'assets/images/globe.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'Star',
		image: 'assets/images/star.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'Country Weekly',
		image: 'assets/images/country_weekly.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},

// News & Entertainment
	{
		title: 'In Touch Weekly',
		image: 'assets/images/in_touch_weekly.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'Life & Style',
		image: 'assets/images/life_style.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'OK Magazine',
		image: 'assets/images/ok_magazine.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'People Weekly',
		image: 'assets/images/people_weekly.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
		order: 'unselected',
	},
	{
		title: 'Soap Opera Digest',
		image: 'assets/images/soap_opera_digest.jpg',
		genre: '02 - News & Entertainment',
		minorder: '2',
		frequency: 'W',
		order: 'unselected',
	},
];